project_name: metrics-bench-suite

builds:
  - id: loader
    main: ./cmd/loader
    binary: loader
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
  - id: remote_write_request_viewer
    main: ./cmd/remote_write_request_viewer
    binary: remote_write_request_viewer
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
  - id: timeseries_analyzer
    main: ./cmd/timeseries_analyzer
    binary: timeseries_analyzer
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64

archives:
  - id: archive
    builds:
      - loader
      - remote_write_request_viewer
      - timeseries_analyzer
    format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    files:
      - LICENSE
      - README.md

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - Update README.md
      - Merge pull request
      - Merge branch