end: '2021-01-01T00:00:00Z'
fields:
- dist:
    lower_bound: 1
    step: 10
    type: mono_inc
    upper_bound: 1000
  name: greptime_value
  type: Float
interval: 30
precision: 1000
start: '2021-01-01T00:00:00Z'
tags:
- dist:
    type: constant_string
    value: eks-us-east-1-qa1
  name: cluster
  type: String
- dist:
    type: constant_string
    value: kube-state-metrics
  name: container
  type: String
- dist:
    preset:
    - value: StatefulSet
      weight: 1
    type: weighted_preset
  name: created_by_kind
  type: String
- dist:
    preset:
    - value: created_by_name
      weight: 1
    type: weighted_preset
  name: created_by_name
  type: String
- dist:
    type: constant_string
    value: http
  name: endpoint
  type: String
- dist:
    type: constant_string
    value: qa
  name: env
  type: String
- dist:
    type: constant_string
    value: 'false'
  name: holiday
  type: String
- dist:
    preset:
    - value: 10.0.162.53
      weight: 1
    type: weighted_preset
  name: host_ip
  type: String
- dist:
    preset:
    - value: 'false'
      weight: 1
    type: weighted_preset
  name: host_network
  type: String
- dist:
    type: constant_string
    value: 10.0.169.98:8080
  name: instance
  type: String
- dist:
    type: constant_string
    value: kube-state-metrics
  name: job
  type: String
- dist:
    preset:
    - value: ingress-nginx
      weight: 1
    type: weighted_preset
  name: namespace
  type: String
- dist:
    preset:
    - value: ip-10-0-162-53.ec2.internal
      weight: 1
    type: weighted_preset
  name: node
  type: String
- dist:
    preset:
    - value: ingress-nginx-controller-646d774bc8-frtzs
      weight: 1
    type: weighted_preset
  name: pod
  type: String
- dist:
    preset:
    - value: 10.0.171.17
      weight: 1
    type: weighted_preset
  name: pod_ip
  type: String
- dist:
    preset:
    - value: system-cluster-critical
      weight: 1
    type: weighted_preset
  name: priority_class
  type: String
- dist:
    type: constant_string
    value: monitoring/prometheus-kube-prometheus-prometheus
  name: prometheus
  type: String
- dist:
    type: constant_string
    value: prometheus-prometheus-kube-prometheus-prometheus-0
  name: prometheus_replica
  type: String
- dist:
    type: constant_string
    value: prometheus-kube-state-metrics
  name: service
  type: String
- dist:
    preset:
    - value: 438ceb9c-52bb-4988-bf02-f676fa4f25bc
      weight: 1
    type: weighted_preset
  name: uid
  type: String
- dist:
    preset:
    type: replica_string
    replica: 20
    replica_prefix: extra-
  name: extra
  type: String
- dist:
    preset:
    type: replica_string
    replica: 20
    replica_prefix: uid-
  name: uuid
  type: String
