end: '2021-01-01T00:00:00Z'
fields:
- dist:
    lower_bound: 1
    step: 10
    type: mono_inc
    upper_bound: 1000
  name: greptime_value
  type: Float
interval: 30
precision: 1000
start: '2021-01-01T00:00:00Z'
tags:
- dist:
    type: constant_string
    value: eks-us-east-1-qa1
  name: cluster
  type: String
- dist:
    preset:
    - value: controller
      weight: 1
    type: weighted_preset
  name: container
  type: String
- dist:
    preset:
    - value: /dev/nvme0n1
      weight: 1
    type: weighted_preset
  name: device
  type: String
- dist:
    type: constant_string
    value: https-metrics
  name: endpoint
  type: String
- dist:
    type: constant_string
    value: qa
  name: env
  type: String
- dist:
    type: constant_string
    value: 'false'
  name: holiday
  type: String
- dist:
    preset:
    - value: /kubepods.slice/kubepods-burstable.slice/kubepods-burstable-pod6eaa4967_0c53_492a_9343_8f7d279664ea.slice/cri-containerd-dfcb74191583d65d4ede0e3206c844f91cdb28bdb9ef4076a1a9753d0b12e491.scope
      weight: 1
    type: weighted_preset
  name: id
  type: String
- dist:
    preset:
    - value: docker.io/bitnami/sealed-secrets-controller:0.26.0
      weight: 1
    - value: docker.io/victoriametrics/vmstorage:v1.94.0-cluster
      weight: 1
    - value: docker.io/bitnami/etcd:3.5.9-debian-11-r4
      weight: 1
    - value: quay.io/argoproj/argocli:v3.5.1
      weight: 1
    - value: 465927837118.dkr.ecr.us-east-1.amazonaws.com/greptime/greptimedb:v0.11.2
      weight: 1
    - value: null
      weight: 1
    - value: 465927837118.dkr.ecr.us-east-1.amazonaws.com/greptimeteam/dashboard-private:60b6c415-playground-test
      weight: 1
    - value: public.ecr.aws/eks-distro/kubernetes-csi/livenessprobe:v2.13.0-eks-1-30-10
      weight: 1
    - value: docker.io/timberio/vector:0.42.0-distroless-libc
      weight: 1
    - value: 066635153087.dkr.ecr.il-central-1.amazonaws.com/eks/kube-proxy:v1.30.6-minimal-eksbuild.3
      weight: 1
    - value: 465927837118.dkr.ecr.us-east-1.amazonaws.com/greptimeteam/greptimedb-cloud:d78af306
      weight: 1
    - value: public.ecr.aws/eks-distro/kubernetes-csi/node-driver-registrar:v2.10.0-eks-1-29-7
      weight: 1
    - value: docker.io/grafana/loki:2.9.5
      weight: 1
    - value: public.ecr.aws/ebs-csi-driver/volume-modifier-for-k8s:v0.3.0
      weight: 1
    - value: public.ecr.aws/ebs-csi-driver/aws-ebs-csi-driver:v1.34.0
      weight: 1
    - value: public.ecr.aws/eks-distro/kubernetes-csi/node-driver-registrar:v2.11.0-eks-1-30-10
      weight: 1
    - value: quay.io/prometheus/prometheus:v2.47.2
      weight: 1
    - value: public.ecr.aws/eks-distro/kubernetes-csi/livenessprobe:v2.12.0-eks-1-29-7
      weight: 1
    - value: public.ecr.aws/eks-distro/kubernetes-csi/external-provisioner:v4.0.0-eks-1-29-7
      weight: 1
    - value: 602401143452.dkr.ecr.us-east-1.amazonaws.com/eks/pause:3.5
      weight: 1
    type: weighted_preset
  name: image
  type: String
- dist:
    preset:
    - value: 10.0.169.179:10250
      weight: 1
    type: weighted_preset
  name: instance
  type: String
- dist:
    type: constant_string
    value: kubelet
  name: job
  type: String
- dist:
    type: constant_string
    value: /metrics/cadvisor
  name: metrics_path
  type: String
- dist:
    preset:
    - value: dfcb74191583d65d4ede0e3206c844f91cdb28bdb9ef4076a1a9753d0b12e491
      weight: 1
    type: weighted_preset
  name: name
  type: String
- dist:
    preset:
    - value: sealed-secrets
      weight: 1
    - value: victoria-metrics-cluster
      weight: 1
    - value: dedicated-etcd
      weight: 1
    - value: argo-workflows
      weight: 1
    - value: greptimedb-standalone
      weight: 1
    - value: greptimedb
      weight: 1
    - value: etcd
      weight: 1
    - value: kube-system
      weight: 1
    - value: vector
      weight: 1
    - value: monitoring
      weight: 1
    - value: loki
      weight: 1
    - value: cert-manager
      weight: 1
    - value: tempo
      weight: 1
    - value: argo-cd
      weight: 1
    - value: external-dns
      weight: 1
    - value: gcpa
      weight: 1
    - value: jarvis
      weight: 1
    - value: robusta
      weight: 1
    - value: gcp
      weight: 1
    - value: internal-ingress-nginx
      weight: 1
    type: weighted_preset
  name: namespace
  type: String
- dist:
    preset:
    - value: ip-10-0-169-179.ec2.internal
      weight: 1
    - value: ip-10-0-175-164.ec2.internal
      weight: 1
    - value: ip-10-0-162-53.ec2.internal
      weight: 1
    - value: ip-10-0-162-77.ec2.internal
      weight: 1
    - value: ip-10-0-166-131.ec2.internal
      weight: 1
    type: weighted_preset
  name: node
  type: String
- dist:
    preset:
    - value: sealed-secrets-5c8744579f-tnvjk
      weight: 1
    - value: victoria-metrics-cluster-vmstorage-1
      weight: 1
    - value: etcd-2
      weight: 1
    - value: argo-workflows-server-d96d86d9c-99qpl
      weight: 1
    - value: greptimedb-standalone-0
      weight: 1
    - value: etcd-1
      weight: 1
    - value: dashboard-playground-5d7c84ffbc-mtffh
      weight: 1
    - value: ebs-csi-controller-7569cdd674-fvqnc
      weight: 1
    - value: vector-n6r8q
      weight: 1
    - value: prometheus-prometheus-kube-prometheus-prometheus-0
      weight: 1
    - value: greptimedb-datanode-1
      weight: 1
    - value: greptimedb-datanode-2
      weight: 1
    - value: kube-proxy-9r8vq
      weight: 1
    - value: greptimedb-flownode-0
      weight: 1
    - value: kube-proxy-vrnnh
      weight: 1
    - value: efs-csi-node-pnq5t
      weight: 1
    - value: loki-backend-0
      weight: 1
    - value: cert-manager-6b6c8845d7-xvwcj
      weight: 1
    - value: ebs-csi-controller-7569cdd674-whx4z
      weight: 1
    - value: ebs-csi-node-c24t2
      weight: 1
    type: weighted_preset
  name: pod
  type: String
- dist:
    type: constant_string
    value: monitoring/prometheus-kube-prometheus-prometheus
  name: prometheus
  type: String
- dist:
    type: constant_string
    value: prometheus-prometheus-kube-prometheus-prometheus-0
  name: prometheus_replica
  type: String
- dist:
    type: constant_string
    value: prometheus-kube-prometheus-kubelet
  name: service
  type: String
