end: '2021-01-01T00:00:00Z'
fields:
- dist:
    lower_bound: 1
    step: 10
    type: mono_inc
    upper_bound: 1000
  name: greptime_value
  type: Float
interval: 30
precision: 1000
start: '2021-01-01T00:00:00Z'
tags:
- dist:
    type: constant_string
    value: eks-us-east-1-qa1
  name: cluster
  type: String
- dist:
    preset:
    - value: container
      weight: 1
    type: weighted_preset
  name: container
  type: String
- dist:
    preset:
    - value: /dev/nvme0n1
      weight: 1
    - value: /dev/nvme0n2
      weight: 1
    type: weighted_preset
  name: device
  type: String
- dist:
    type: constant_string
    value: https-metrics
  name: endpoint
  type: String
- dist:
    type: weighted_preset
    preset:
    - value: qa
      weight: 1
    - value: prod
      weight: 1
  name: env
  type: String
- dist:
    type: constant_string
    value: 'false'
  name: holiday
  type: String
- dist:
    preset:
    - value: /kubepods.slice/kubepods-burstable.slice/kubepods-burstable-podc2d3be1c_1b19_43ef_a5cf_a296cb2ad1ef.slice/cri-containerd-ea3cf7abfb77f669b023908e296195fbd3f12a7dcd49db0f2da0f5311e4d14c6.scope
      weight: 1
    type: weighted_preset
  name: id
  type: String
- dist:
    preset:
    - value: 602401143452.dkr.ecr.us-east-1.amazonaws.com/eks/pause:3.5
      weight: 1
    type: weighted_preset
  name: image
  type: String
- dist:
    preset:
    - value: 10.0.166.131:10250
      weight: 1
    - value: 10.0.175.164:10250
      weight: 1
    - value: 10.0.162.53:10250
      weight: 1
    - value: 10.0.169.179:10250
      weight: 1
    - value: 10.0.162.77:10250
      weight: 1
    type: weighted_preset
  name: instance
  type: String
- dist:
    type: constant_string
    value: kubelet
  name: job
  type: String
- dist:
    type: constant_string
    value: /metrics/cadvisor
  name: metrics_path
  type: String
- dist:
    preset:
    - value: ea3cf7abfb77f669b023908e296195fbd3f12a7dcd49db0f2da0f5311e4d14c6
      weight: 1
    - value: 28579a0d259ec3665b5740b9b85415384704d8ce55aab49b407cdb07007d0991
      weight: 1
    - value: 46d9ab51549fbdb7a72ac217a7ab6475a80ee2ae811e0156b0334e91fa3a263a
      weight: 1
    - value: null
      weight: 1
    - value: f8d5ce73cf1135a1feefd91058b8b28dc9eeb324686e56252a906501c47d0755
      weight: 1
    - value: 2c484690618aff701cd38e18bed7faba29815a83cc5ddba248aa42ac93bb6485
      weight: 1
    - value: 46f66160d45b8fb003db6338b3c74a86aea46e68f3447f5a49fe3d0679bf53af
      weight: 1
    - value: 0198a7ed60a520c220d599def1f8bdaba84df761fd75dc70982d2d81b0fdfa0d
      weight: 1
    - value: b9afbc1ca38342723e7948d48f7033a976dcf5c4bb9bd2bb80d422fb4e74d5fe
      weight: 1
    - value: 1522beb632cbaf4ccfa118e49b45b012aee9734da39b3555046861a3dd397847
      weight: 1
    - value: f9e409a316e431b59744a713b50cffd56f7aba5897eb466465b51cbcf466c034
      weight: 1
    - value: b871741ed5ea0e1f46cb4284b4ae4e7ed075ef7c55bab71b61ec50303258b7dd
      weight: 1
    - value: ab44f6464bd80dddabf7e97449698f1355566d49bf745356db5f3436df6655d9
      weight: 1
    - value: dbacfe1ddb8cfa7b1678d9aa6278dd848b8c7966dcce7d574d424291025fead4
      weight: 1
    - value: af0bab1b78537559418d2409fae9cfecdedcd7e806d66d3fca1ba4a083540def
      weight: 1
    - value: 882055bc2e4b70c6bcbb1d3bfe3cef17832d7e054d759d21932c07e0b8ec47cd
      weight: 1
    - value: a8bc2e722eedc9f10b40e39dc5f656c2721e8bc7eb69fc6cd15babcea2355a15
      weight: 1
    - value: 85e31c8e90ea2ec5f4ce60a050de6f48fe7ec587197d1b3caf543ba710e4d028
      weight: 1
    - value: d3af0602ea96307e5cc616b6b921f284eb9d420370f54bc3db4d20a91d528b82
      weight: 1
    - value: dbfabeda70701c170e5230f2c6b3c0356cb15a05d5446d12e63bc91b1985c22f
      weight: 1
    type: weighted_preset
  name: name
  type: String
- dist:
    preset:
    - value: victoria-metrics-cluster
      weight: 1
    - value: kube-system
      weight: 1
    - value: dedicated-etcd
      weight: 1
    - value: tempo
      weight: 1
    - value: sealed-secrets
      weight: 1
    - value: greptimedb
      weight: 1
    - value: internal-ingress-nginx
      weight: 1
    - value: cert-manager
      weight: 1
    - value: loki
      weight: 1
    - value: etcd
      weight: 1
    - value: vector
      weight: 1
    - value: gcp
      weight: 1
    - value: monitoring
      weight: 1
    - value: kubernetes-event-exporter
      weight: 1
    - value: tudigong
      weight: 1
    - value: bytebase
      weight: 1
    - value: argo-cd
      weight: 1
    - value: kubernetes-replicator
      weight: 1
    - value: robusta
      weight: 1
    - value: kube-fledged
      weight: 1
    type: weighted_preset
  name: namespace
  type: String
- dist:
    preset:
    - value: ip-10-0-166-131.ec2.internal
      weight: 1
    - value: ip-10-0-175-164.ec2.internal
      weight: 1
    - value: ip-10-0-162-53.ec2.internal
      weight: 1
    - value: ip-10-0-169-179.ec2.internal
      weight: 1
    - value: ip-10-0-162-77.ec2.internal
      weight: 1
    type: weighted_preset
  name: node
  type: String
- dist:
    preset:
    - value: victoria-metrics-cluster-vmselect-775df7c778-lkm8n
      weight: 1
    - value: ebs-csi-node-h64gd
      weight: 1
    - value: ebs-csi-node-2ffjx
      weight: 1
    - value: etcd-1
      weight: 1
    - value: tempo-0
      weight: 1
    - value: efs-csi-node-x2ht5
      weight: 1
    - value: sealed-secrets-5c8744579f-tnvjk
      weight: 1
    - value: aws-load-balancer-controller-6896d97fcf-897cz
      weight: 1
    - value: dashboard-75f8f745cf-rvtq7
      weight: 1
    - value: ebs-csi-node-297wb
      weight: 1
    - value: internal-ingress-nginx-controller-76d547b95b-lvzhp
      weight: 1
    - value: cert-manager-webhook-87b57d98b-48p4n
      weight: 1
    - value: loki-write-1
      weight: 1
    - value: aws-node-mpvsz
      weight: 1
    - value: ebs-csi-node-qkksr
      weight: 1
    - value: loki-backend-1
      weight: 1
    - value: etcd-2
      weight: 1
    - value: ebs-csi-controller-7569cdd674-fvqnc
      weight: 1
    - value: greptimedb-datanode-0
      weight: 1
    - value: vector-dbg5j
      weight: 1
    type: weighted_preset
  name: pod
  type: String
- dist:
    type: constant_string
    value: monitoring/prometheus-kube-prometheus-prometheus
  name: prometheus
  type: String
- dist:
    type: constant_string
    value: prometheus-prometheus-kube-prometheus-prometheus-0
  name: prometheus_replica
  type: String
- dist:
    type: constant_string
    value: prometheus-kube-prometheus-kubelet
  name: service
  type: String
