end: '2021-01-01T00:00:00Z'
fields:
- dist:
    lower_bound: 1
    step: 10
    type: mono_inc
    upper_bound: 1000
  name: greptime_value
  type: Float
interval: 30
precision: 1000
start: '2021-01-01T00:00:00Z'
tags:
- dist:
    type: constant_string
    value: eks-us-east-1-qa1
  name: cluster
  type: String
- dist:
    preset:
    - value: repo-server
      weight: 1
    type: weighted_preset
  name: container
  type: String
- dist:
    type: constant_string
    value: total
  name: cpu
  type: String
- dist:
    type: constant_string
    value: https-metrics
  name: endpoint
  type: String
- dist:
    type: constant_string
    value: qa
  name: env
  type: String
- dist:
    type: constant_string
    value: 'false'
  name: holiday
  type: String
- dist:
    preset:
    - value: id
      weight: 1
    type: weighted_preset
  name: id
  type: String
- dist:
    preset:
    - value: quay.io/argoproj/argocd:v2.10.1
      weight: 1
    type: weighted_preset
  name: image
  type: String
- dist:
    preset:
    - value: 10.0.169.179:10250
      weight: 1
    - value: 10.0.162.77:10250
      weight: 1
    - value: 10.0.162.53:10250
      weight: 1
    - value: 10.0.166.131:10250
      weight: 1
    - value: 10.0.175.164:10250
      weight: 1
    type: weighted_preset
  name: instance
  type: String
- dist:
    type: constant_string
    value: kubelet
  name: job
  type: String
- dist:
    type: constant_string
    value: /metrics/cadvisor
  name: metrics_path
  type: String
- dist:
    preset:
    - value: name
      weight: 1
    type: weighted_preset
  name: name
  type: String
- dist:
    preset:
    - value: argo-cd
      weight: 1
    type: weighted_preset
  name: namespace
  type: String
- dist:
    preset:
    - value: ip-10-0-169-179.ec2.internal
      weight: 1
    type: weighted_preset
  name: node
  type: String
- dist:
    preset:
    - value: argo-cd-argocd-repo-server-848d887764-d9cgv
      weight: 1
    type: weighted_preset
  name: pod
  type: String
- dist:
    type: constant_string
    value: monitoring/prometheus-kube-prometheus-prometheus
  name: prometheus
  type: String
- dist:
    type: constant_string
    value: prometheus-prometheus-kube-prometheus-prometheus-0
  name: prometheus_replica
  type: String
- dist:
    type: constant_string
    value: prometheus-kube-prometheus-kubelet
  name: service
  type: String
