end: '2021-01-01T00:00:00Z'
fields:
- dist:
    lower_bound: 1
    step: 10
    type: mono_inc
    upper_bound: 1000
  name: greptime_value
  type: Float
interval: 30
precision: 1000
start: '2021-01-01T00:00:00Z'
tags:
- dist:
    type: weighted_preset
    preset:
    - value: eks-us-east-1-qa1
      weight: 1
    - value: eks-us-east-1-prod
      weight: 1
    - value: eks-us-east-1-test
      weight: 1
  name: cluster
  type: String
- dist:
    type: constant_string
    value: kube-state-metrics
  name: namespace
  type: String
