end: '2021-01-01T00:00:00Z'
fields:
- dist:
    lower_bound: 1
    step: 10
    type: mono_inc
    upper_bound: 1000
  name: greptime_value
  type: Float
interval: 30
precision: 1000
start: '2021-01-01T00:00:00Z'
tags:
- dist:
    type: constant_string
    value: eks-us-east-1-qa1
  name: cluster
  type: String
- dist:
    preset:
    - value: container
      weight: 1
    type: weighted_preset
  name: container
  type: String
- dist:
    type: constant_string
    value: https-metrics
  name: endpoint
  type: String
- dist:
    type: constant_string
    value: qa
  name: env
  type: String
- dist:
    type: constant_string
    value: 'false'
  name: holiday
  type: String
- dist:
    preset:
    - value: id
      weight: 1
    type: weighted_preset
  name: id
  type: String
- dist:
    preset:
    - value: image
      weight: 1
    type: weighted_preset
  name: image
  type: String
- dist:
    preset:
    - value: 10.0.175.164:10250
      weight: 1
    - value: 10.0.166.131:10250
      weight: 1
    - value: 10.0.162.77:10250
      weight: 1
    - value: 10.0.162.53:10250
      weight: 1
    - value: 10.0.169.179:10250
      weight: 1
    type: weighted_preset
  name: instance
  type: String
- dist:
    type: constant_string
    value: kubelet
  name: job
  type: String
- dist:
    type: constant_string
    value: /metrics/cadvisor
  name: metrics_path
  type: String
- dist:
    preset:
    - value: name0
    type: weighted_preset
  name: name
  type: String
- dist:
    preset:
    - value: bytebase
      weight: 1
    - value: kube-system
      weight: 1
    - value: vector
      weight: 1
    - value: ingress-nginx
      weight: 1
    - value: monitoring
      weight: 1
    - value: gcp
      weight: 1
    - value: external-dns
      weight: 1
    - value: kafka
      weight: 1
    - value: gcrm
      weight: 1
    - value: gcpa
      weight: 1
    - value: greptimedb
      weight: 1
    - value: loki
      weight: 1
    - value: argo-cd
      weight: 1
    - value: greptimedb-operator
      weight: 1
    - value: internal-greptimedb-standalone
      weight: 1
    - value: victoria-metrics-cluster
      weight: 1
    - value: jarvis
      weight: 1
    - value: kubernetes-event-exporter
      weight: 1
    - value: reloader
      weight: 1
    - value: etcd
      weight: 1
    type: weighted_preset
  name: namespace
  type: String
- dist:
    preset:
    - value: ip-10-0-175-164.ec2.internal
      weight: 1
    - value: ip-10-0-166-131.ec2.internal
      weight: 1
    - value: ip-10-0-162-77.ec2.internal
      weight: 1
    - value: ip-10-0-162-53.ec2.internal
      weight: 1
    - value: ip-10-0-169-179.ec2.internal
      weight: 1
    type: weighted_preset
  name: node
  type: String
- dist:
    preset:
    - value: bytebase-0
      weight: 1
    - value: efs-csi-node-7ln4t
      weight: 1
    - value: vector-2xvqg
      weight: 1
    - value: ingress-nginx-controller-646d774bc8-frtzs
      weight: 1
    - value: prometheus-prometheus-node-exporter-bpscm
      weight: 1
    - value: gcp-6fbc9cf564-k5968
      weight: 1
    - value: external-dns-5c99648766-lcjg4
      weight: 1
    - value: kafka-controller-0
      weight: 1
    - value: ingress-nginx-controller-646d774bc8-7qvh7
      weight: 1
    - value: gcrm-c9598d7f-hrrv2
      weight: 1
    - value: prometheus-kube-prometheus-operator-7dc7f7857d-9gcjt
      weight: 1
    - value: ebs-csi-node-qkksr
      weight: 1
    - value: gcpa-mtls-6c446fbd88-xbkhr
      weight: 1
    - value: vector-qwpl5
      weight: 1
    - value: greptimedb-flownode-0
      weight: 1
    - value: prometheus-prometheus-node-exporter-bzhjw
      weight: 1
    - value: efs-csi-controller-bc466c4b6-2542z
      weight: 1
    - value: efs-csi-node-l4rxj
      weight: 1
    - value: loki-backend-1
      weight: 1
    - value: loki-backend-0
      weight: 1
    type: weighted_preset
  name: pod
  type: String
- dist:
    type: constant_string
    value: monitoring/prometheus-kube-prometheus-prometheus
  name: prometheus
  type: String
- dist:
    type: constant_string
    value: prometheus-prometheus-kube-prometheus-prometheus-0
  name: prometheus_replica
  type: String
- dist:
    type: constant_string
    value: prometheus-kube-prometheus-kubelet
  name: service
  type: String
